- hosts: all
  gather_facts: no
  tasks:
  - name: win_package install firefox
    win_package:
      path: C:\Users\ansible\Downloads\Firefox%20Installer.exe
      product_id: 'Mozilla Firefox'
      state: present
      arguments: /install /passive /norestart
